Repository sberbankjavaschool/homework, pull requests merged in 2019-05, with the labels that each got.

#24 (2) Таргон
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalculator.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryForCurrCalc.java
Labels: OK

#29 (2) Naumovec
  solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
  solutions/src/main/java/ru/sberbank/school/task02/CalculatorFactory.java
  solutions/src/main/java/ru/sberbank/school/task02/EmptyQuoteException.java
  solutions/src/main/java/ru/sberbank/school/task02/Solution.java
Labels: OK

#33 (2) Лобанова
  solutions/src/main/java/ru/sberbank/school/task02/Converter.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
Labels: OK

#47 (2) Malygin
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
Labels: OK

#43 (2) Romanova
  solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/Test.java
Labels: OK

#39 (2) Zahoda
  solutions/src/main/java/ru/sberbank/school/task02/Converter.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
Labels: OK

#42 (2) Malouhov
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  tasks/src/main/java/ru/sberbank/school/task02/util/ExternalQuotesServiceDemo2.java
Labels: OK

#56 (2) Fedorov
  homework.iml
  solutions/src/main/java/ru/sberbank/school/task02/exception/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/exception/ServiceFactoryImpl.java
Labels: OK

#53 (2) Маврин
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalc.java
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalcFactory.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
Labels: OK

#81 (4) Южаков
  solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
  solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesProvider.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  solutions/src/test/java/ru/sberbank/school/task02/CalculatorTest.java
  solutions/src/test/java/ru/sberbank/school/task02/ReverseCalculatorTest.java
Labels: OK, Ждет проверки

#60 (2) Batyrev
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/SimpleFxConversionService.java
Labels: OK

#95 (4) Таргон
  solutions/src/main/java/ru/sberbank/school/task02/Client.java
  solutions/src/main/java/ru/sberbank/school/task02/ClientExample.java
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalculator.java
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryForCurrCalc.java
Labels: OK

#122 (4) Malouhov
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task03/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task03/FxRequestConversionService.java
  solutions/src/main/java/ru/sberbank/school/task03/FxRequestConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task03/Main.java
  tasks/src/main/java/ru/sberbank/school/task02/util/ExternalQuotesServiceDemo2.java
Labels: OK

#116 (4) Malygin
  solutions/src/main/java/ru/sberbank/school/task02/Client.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxRequestConverter.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
Labels: OK

#110 (3, 4) Naumovec
  solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
  solutions/src/main/java/ru/sberbank/school/task02/CalculatorFactory.java
  solutions/src/main/java/ru/sberbank/school/task02/Client.java
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
  solutions/src/main/java/ru/sberbank/school/task02/Solution.java
  solutions/src/main/java/ru/sberbank/school/task02/exception/EmptyQuoteException.java
  solutions/src/main/java/ru/sberbank/school/task02/util/ReverseQuote.java
  solutions/src/test/java/ru/sberbank/school/task02/CalcTest.java
  solutions/src/test/java/ru/sberbank/school/task02/ExCalcTest.java
Labels: OK

#118 (4) Fedorov
  .gitignore
  solutions/src/main/java/ru/sberbank/school/task02/exception/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/exception/FxConversionServiceImpl.java
Labels: OK

#124 (4) Sychev
  gradle/wrapper/gradle-wrapper.properties
  solutions/src/main/java/ru/sberbank/school/task02/ConverterTests.java
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedFxConverter.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClient.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConverter.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConverterFactory.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/QuotesListNull.java
  solutions/src/main/java/ru/sberbank/school/task02/exception/NullQuotesListException.java
  solutions/src/test/java/ru/sberbank/school/task02/ClientExceptionTests.java
  solutions/src/test/java/ru/sberbank/school/task02/ConverterTests.java
Labels: OK

#130 (4) Zahoda
  solutions/src/main/java/ru/sberbank/school/task02/ClientController.java
  solutions/src/main/java/ru/sberbank/school/task02/Converter.java
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedConverterService.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/util/RequesParser.java
Labels: OK

#117 (4) Martyanov
  solutions/src/main/java/ru/sberbank/school/task02/Client.java
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedFxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxRequestConverter.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
Labels: OK

#84 (2) Bedarev
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CompareQutes.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CurrencyCalculator.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CurrencyCalculatorBuilder.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CustomExternalQutesService.java
Labels: OK

#94 (5) Romanova
  common/build.gradle
  common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
  solutions/build.gradle
  solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxRequestCheck.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/Test.java
Labels: OK

#137 (5) Южаков
  common/build.gradle
  common/src/main/groovy/ru/sberbank/school/task03/Formatter.groovy
  solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
  solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesProvider.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
  solutions/src/test/java/ru/sberbank/school/task02/FxClientControllerImplTest.java
  solutions/src/test/java/ru/sberbank/school/task02/ReverseCalculatorTest.java
  solutions/src/test/java/ru/sberbank/school/task03/FormatterTest.java
Labels: OK

#153 (5) Malygin
  common/build.gradle
  common/src/main/groovy/ru/sberbank/school/task03/FormatterTemplate.groovy
  common/src/main/groovy/ru/sberbank/school/task03/ResponseConverter.groovy
  common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
  settings.gradle
  solutions/build.gradle
Labels: OK

#154 (5) Горских
  common/build.gradle
  common/src/main/groovy/ru/sberbank/school/task03/Formatter.groovy
  common/src/main/groovy/ru/sberbank/school/task03/Report.groovy
  common/src/main/groovy/ru/sberbank/school/task03/ReportGenerator.groovy
  solutions/src/main/java/ru/sberbank/school/task02/Client.java
  solutions/src/main/java/ru/sberbank/school/task02/TestClient.java
  solutions/src/main/java/ru/sberbank/school/task02/calculators/ExtendedCurrencyCalc.java
Labels: OK

#157 (5) Лобанова
  common/build.gradle
  common/src/main/groovy/ru.sberbank.school/task03/Formatter.groovy
  common/src/main/groovy/ru.sberbank.school/task03/ModelCalculation.groovy
  common/src/main/groovy/ru.sberbank.school/task03/model/DocumentInfo.groovy
  common/src/main/groovy/ru.sberbank.school/task03/model/SymbolRequestInfo.groovy
  common/src/main/groovy/ru.sberbank.school/task03/model/VolumeRequestInfo.groovy
Labels: OK

#162 (5) Zahoda
  common/build.gradle
  common/src/main/java/ru/sberbank/school/task02/BlockData.groovy
  common/src/main/java/ru/sberbank/school/task02/ResponseFormatterImpl.groovy
  common/src/main/java/ru/sberbank/school/task02/util/PairPriceAmount.groovy
  common/src/main/java/ru/sberbank/school/task02/util/RequestParser.java
  solutions/src/main/java/ru/sberbank/school/task02/ClientController.java
  solutions/src/main/java/ru/sberbank/school/task02/Converter.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/util/CurrentDate.java
Labels: OK

#150 (5) Melnikov
  common/build.gradle
  common/src/main/groovy/ru/sberbank/school/task03/model/ResponseReportModel.groovy
  common/src/main/groovy/ru/sberbank/school/task03/util/ResponseFormatterImpl.groovy
  common/src/main/groovy/ru/sberbank/school/task03/util/ResponseFormatterImplOld.groovy
  common/src/main/groovy/ru/sberbank/school/task03/util/ResponseModelConverter.groovy
  settings.gradle
  solutions/src/main/java/ru/sberbank/school/task02/FxClient.java
  solutions/src/main/java/ru/sberbank/school/task02/controllers/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/enums/Symbols.java
  solutions/src/main/java/ru/sberbank/school/task02/exeption/BuildRequestsNeverCallException.java
  solutions/src/main/java/ru/sberbank/school/task02/exeption/BuildRequestsNeverCallExeption.java
  solutions/src/main/java/ru/sberbank/school/task02/exeption/EmptyQuoteListException.java
  solutions/src/main/java/ru/sberbank/school/task02/services/implementation/ExtendedFxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/services/implementation/InternalQuotesServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/util/FxRequestBuilder.java
  solutions/src/main/java/ru/sberbank/school/task02/validators/AmountPositiveValidator.java
Labels: OK

#156 (5) Таргон
  common/build.gradle
  common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
  common/src/main/groovy/ru/sberbank/school/task03/util/DataFromResponse.groovy
  common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
  common/src/main/groovy/ru/sberbank/school/task03/util/Pair.groovy
Labels: OK

#178 (3) Лобанова
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedConverter.java
Labels: OK

#166 (5) Fedorov
  common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
  common/src/main/groovy/ru/sberbank/school/task03/SolutionFormatter.groovy
  solutions/build.gradle
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
  tasks/src/main/java/ru/sberbank/school/task03/readme.md
Labels: OK

#205 (3, 4) Romanova
  solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/Test.java
Labels: OK, Ждет проверки

#223 (6) Лобанова
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
  solutions/src/main/java/ru/sberbank/school/task06/Pet.java
Labels: OK

#226 (7) Горских
  common/build.gradle
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/WordsFrequencyImpl.java
  tasks/src/main/java/ru/sberbank/school/task07/Counter.java
  tasks/src/main/java/ru/sberbank/school/task07/DifferentWords.java
  tasks/src/main/java/ru/sberbank/school/task07/FileParser.java
  tasks/src/main/java/ru/sberbank/school/task07/WordFrequency.java
Labels: OK

#210 (2) Bzhosko
  solutions/src/main/java/ru/sberbank/school/task02/service/ExternalQuotesServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/service/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/service/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/service/ServiceFactoryImpl.java
Labels: OK, REBASE NEEDED, Squash me!

#173 (3) Bedarev
  settings.gradle
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CompareQuotesBeneficiary.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CompareQutesExtend.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CurrencyCalculatorBuilder.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/CustomExternalQutesService.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/ExtendedCurrencyCalculator.java
  tasks/src/main/java/ru/sberbank/school/task02/calculator/QuotePrice.java
Labels: OK

#235 (3) Malygin
  solutions/src/main/java/ru/sberbank/school/task02/Client.java
  solutions/src/main/java/ru/sberbank/school/task02/ExtendedFxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
Labels: OK

#229 (4, 5) Mavrin
  build.gradle
  common/src/main/groovy/ru.sberbank.school/task03/Controller.groovy
  common/src/main/groovy/ru.sberbank.school/task03/Formatter.groovy
  common/src/main/groovy/ru.sberbank.school/task03/Template.groovy
  common/src/main/groovy/ru.sberbank.school/task03/model/DocumentInfo.groovy
  common/src/main/groovy/ru.sberbank.school/task03/model/SymbolRequestInfo.groovy
  common/src/main/groovy/ru.sberbank.school/task03/model/VolumeRequestInfo.groovy
  solutions/src/main/java/ru/sberbank/school/task02/ClientController.java
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalc.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/util/ArgumentParser.java
Labels: OK, Ждет проверки

#247 (6) Naumovets
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
  solutions/src/main/java/ru/sberbank/school/task06/Dog.java
  solutions/src/main/java/ru/sberbank/school/task06/Pet.java
  solutions/src/main/java/ru/sberbank/school/task08/state/GameObject.java
  solutions/src/main/java/ru/sberbank/school/task08/state/MapState.java
Labels: OK

#256 (6, 7) Fedorov
  homework.iml
  solutions/build.gradle
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalc.java
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalcFactory.java
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/SentenceParser.java
  solutions/src/main/java/ru/sberbank/school/task07/WordsFrequencyImpl.java
  tasks/src/main/java/ru/sberbank/school/task03/readme.md
Labels: OK

#240 (6) Malygin
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
Labels: OK

#245 (6) Затирко
  common/build.gradle
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/ICountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/ICountMapImpl.java
Labels: OK

#258 (8) Romanova
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
  solutions/src/main/java/ru/sberbank/school/task08/JacksonManager.java
  solutions/src/main/java/ru/sberbank/school/task08/KryoManager.java
  solutions/src/main/java/ru/sberbank/school/task08/KryoSerializer.java
  solutions/src/main/java/ru/sberbank/school/task08/SerializableManager.java
  solutions/src/main/java/ru/sberbank/school/task08/state/GameObject.java
  solutions/src/main/java/ru/sberbank/school/task08/state/MapState.java
  solutions/src/test/java/ru/sberbank/school/task08/JacksonManagerTest.java
  solutions/src/test/java/ru/sberbank/school/task08/KryoManagerTest.java
  solutions/src/test/java/ru/sberbank/school/task08/SerializableManagerTest.java
Labels: OK

#261 (2, 3)Bzhosko
  solutions/src/main/java/ru/sberbank/school/task02/service/ExtendedFxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/service/ExternalQuotesServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/service/FxConversionServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task02/service/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/service/ServiceFactoryImpl.java
Labels: OK

#264 (7) Naumovets
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/WordsFrequencyImpl.java
Labels: OK

#265 (3) Mavrin
  common/src/main/groovy/ru.sberbank.school/task03/Controller.groovy
  common/src/main/groovy/ru.sberbank.school/task03/Template.groovy
  solutions/src/main/java/ru/sberbank/school/task02/ClientController.java
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalc.java
  solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalcFactory.java
  solutions/src/main/java/ru/sberbank/school/task02/Main.java
  solutions/src/main/java/ru/sberbank/school/task02/ReversedCurrencyCalc.java
  solutions/src/main/java/ru/sberbank/school/task02/util/ArgumentParser.java
  solutions/src/main/java/ru/sberbank/school/task02/util/ReversedQuote.java
Labels: OK

#269 (7) Malygin
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/WordFrequencyImpl.java
Labels: OK
