Repository sberbankjavaschool/homework, pull requests merged in 2019-06, with the labels that each got.

#271 (9) Romanova
  solutions/src/main/java/ru/sberbank/school/task09/CityKryoSerializer.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteKryoSerializer.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteServiceCached.java
  solutions/src/test/java/ru/sberbank/school/task09/RouteServiceCachedTest.java
Labels: OK

#273 (9) Targon
  solutions/src/main/java/ru/sberbank/school/task08/KryoManager.java
  solutions/src/main/java/ru/sberbank/school/task08/SerializableManager.java
  solutions/src/main/java/ru/sberbank/school/task09/CitySerializer.java
  solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteSerializer.java
  solutions/src/test/java/ru/sberbank/school/task09/KryoRouteServiceTest.java
Labels: OK

#280 (9) Южаков
  solutions/src/main/java/ru/sberbank/school/task09/CacheService.java
  solutions/src/main/java/ru/sberbank/school/task09/CityKryoSerializer.java
  solutions/src/main/java/ru/sberbank/school/task09/KryoCacheService.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteKryoSerializer.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteServiceImpl.java
  solutions/src/test/java/ru/sberbank/school/task09/RouteServiceImplTest.java
Labels: OK

#278 (7) Martyanov
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/Employee.java
  solutions/src/main/java/ru/sberbank/school/task06/MapCounter.java
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/WordsFrequencyImpl.java
  solutions/src/test/java/ru/sberbank/school/task07/CounterImplTest.java
  solutions/src/test/resources/task07.txt
Labels: OK

#291 (10) Горских
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
Labels: OK, Ждет проверки

#288 (10) Romanova
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
Labels: OK

#289 (10) Лобанова
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
Labels: OK

#290 (10) Malygin
  solutions/src/main/java/ru/sberbank/school/task10/AbstractThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
Labels: OK

#294 (10) Naumovets
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/CallableTask.java
  solutions/src/test/java/ru/sberbank/school/task10/RunnableTask.java
  solutions/src/test/java/ru/sberbank/school/task10/ThreadPoolTest.java
  tasks/build.gradle
  tasks/src/main/java/ru/sberbank/school/SchoolTask.java
  tasks/src/main/java/ru/sberbank/school/task09/readme.md
  tasks/src/main/java/ru/sberbank/school/task10/ThreadPool.java
  tasks/src/main/java/ru/sberbank/school/task10/readme.md
Labels: HELP ME, Ждет проверки

#295 (10) Targon
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
Labels: OK

#297 (10) Melnikov
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
Labels: OK

#298 (10) Южаков
  solutions/src/main/java/ru/sberbank/school/task09/CacheService.java
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/MortalThreadPoolWorker.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ThreadPoolWorker.java
  solutions/src/test/java/ru/sberbank/school/task09/RouteServiceImplTest.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
Labels: OK, Ждет проверки

#315 (11) Zahoda
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentFixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentFixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentScalableThreadPoolTest.java
Labels: OK

#310 (11) Romanova
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPoolConcurrent.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPoolConcurrent.java
  solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolConcurrentTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolConcurrentTest.java
Labels: OK

#316 (11) Лобанова
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentFixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentFixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentScalableThreadPoolTest.java
Labels: OK

#317 (11) Naumovets
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentFixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/CallableTask.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentFixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentScalableThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/RunnableTask.java
Labels: OK

#304 (11) Melnikov
  solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task11/ConcurrentFixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task11/ConcurrentScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task11/ConcurrentScalableThreadPoolTest.java
Labels: OK, Проверено

#321 (11) Malygin
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentAbstractThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentFixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentFixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentScalableThreadPoolTest.java
Labels: OK

#309 (12) Южаков
  solutions/src/main/java/ru/sberbank/school/task11/StreamsImpl.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsImplTest.java
Labels: OK

#311 (12) Горских
  solutions/src/main/java/ru/sberbank/school/task11/MyStreams.java
  solutions/src/test/java/ru/sberbank/school/task11/MyStreamsTest.java
Labels: OK

#319 (12) Zahoda
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsTest.java
Labels: OK

#320 (12) Romanova
  solutions/src/main/java/ru/sberbank/school/task11/StreamsImpl.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsImplTest.java
Labels: OK

#330 (12) Лобанова
  solutions/src/main/java/ru/sberbank/school/task11/StreamsImpl.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsImplTest.java
Labels: OK

#331 (12) Targon
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsTest.java
Labels: OK

#329 (12) Naumovets
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsTest.java
Labels: OK

#338 (12) Malygin
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsTest.java
Labels: OK

#323 (11) Targon
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentFixedThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/ConcurrentScalableThreadPool.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentFixedThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/ConcurrentScalableThreadPoolTest.java
Labels: OK

#332 (13) Zahoda
  solutions/src/main/java/ru/sberbank/school/task13/beanfieldcopier/BeanFieldCopierImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/beanfieldcopier/exception/BeanFieldCopierException.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/annotation/Cache.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/annotation/CacheType.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/cache/CacheProxy.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/cache/CacheProxyImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/exception/CacheProxyException.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/serialization/SerializationManager.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/utils/CacheProxyUtils.java
  solutions/src/test/java/ru/sberbank/school/task13/beanfieldcopier/BeanFieldCopierTest.java
  solutions/src/test/java/ru/sberbank/school/task13/beanfieldcopier/model/IntData.java
  solutions/src/test/java/ru/sberbank/school/task13/beanfieldcopier/model/StringData.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/CacheProxyTest.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/services/CacheTest.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/services/CacheTestImpl.java
Labels: OK

#340 (13) Горских
  solutions/src/main/java/ru/sberbank/school/task13/BeanFieldCopierImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/CacheProxy.java
  solutions/src/main/java/ru/sberbank/school/task13/util/Cache.java
  solutions/src/main/java/ru/sberbank/school/task13/util/CacheType.java
  solutions/src/main/java/ru/sberbank/school/task13/util/Handler.java
  solutions/src/test/java/ru/sberbank/school/task13/BeanFieldCopierImplTest.java
  solutions/src/test/java/ru/sberbank/school/task13/CacheProxyTest.java
  solutions/src/test/java/ru/sberbank/school/task13/IUser.java
  solutions/src/test/java/ru/sberbank/school/task13/User.java
Labels: OK

#341 (13) Лобанова
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/CacheProxy.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/Handler.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/annotation/Cache.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/annotation/CacheType.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/exception/CacheProxyException.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/exception/SerializationInCacheException.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/serialization/KryoCacheManager.java
  solutions/src/main/java/ru/sberbank/school/task13/fieldcopier/BeanFieldCopierImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/fieldcopier/exception/BeanFieldCopierException.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/CacheProxyTest.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/ServiceTest.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/ServiceTestInterface.java
  solutions/src/test/java/ru/sberbank/school/task13/fieldcopier/BeanFieldCopierImplTest.java
Labels: OK

#342 (13) Romanova
  solutions/src/main/java/ru/sberbank/school/task13/beanfieldcopier/BeanFieldCopierImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/Cache.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/CacheProxy.java
  solutions/src/main/java/ru/sberbank/school/task13/cacheproxy/CacheSerializatorManager.java
  solutions/src/test/java/ru/sberbank/school/task13/beanfieldcopier/BeanFieldCopierImplTest.java
  solutions/src/test/java/ru/sberbank/school/task13/beanfieldcopier/utils/Player.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/CacheProxyTest.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/utils/TestClass.java
  solutions/src/test/java/ru/sberbank/school/task13/cacheproxy/utils/TestClassImpl.java
Labels: OK

#343 (13) Южаков
  solutions/src/main/java/ru/sberbank/school/task13/BeanFieldCopierImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/CacheProxyImpl.java
  solutions/src/main/java/ru/sberbank/school/task13/CacheType.java
  solutions/src/main/java/ru/sberbank/school/task13/CachingPolicy.java
  solutions/src/main/java/ru/sberbank/school/task13/DefaultInvocationHandler.java
  solutions/src/main/java/ru/sberbank/school/task13/Serializer.java
  solutions/src/test/java/ru/sberbank/school/task13/BeanFieldCopierImplTest.java
  solutions/src/test/java/ru/sberbank/school/task13/CacheProxyImplTest.java
  solutions/src/test/java/ru/sberbank/school/task13/ProperTestSource.java
  solutions/src/test/java/ru/sberbank/school/task13/ProperTestTarget.java
  solutions/src/test/java/ru/sberbank/school/task13/TestClassForCaching.java
  solutions/src/test/java/ru/sberbank/school/task13/TestClassInterface.java
Labels: OK

#324 (09) Melnikov
  solutions/src/main/java/ru/sberbank/school/task09/CachedRouteService.java
  solutions/src/test/java/ru/sberbank/school/task09/CachedRouteServiceTest.java
Labels: OK, ПОМОГИТЕ С РЕВЬЮ

#335 (6) Bzhosko
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
  solutions/src/main/java/ru/sberbank/school/task08/JacksonSerializableManager.java
  solutions/src/main/java/ru/sberbank/school/task08/KryoSerializableManager.java
  solutions/src/main/java/ru/sberbank/school/task08/SerializableManager.java
  solutions/src/main/java/ru/sberbank/school/task08/kryo/MapStateSerializer.java
  solutions/src/main/java/ru/sberbank/school/task08/state/GameObject.java
  solutions/src/main/java/ru/sberbank/school/task08/state/MapState.java
Labels: OK

#336 (7) Bzhosko
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/WordFrequencyImpl.java
Labels: OK

#337 (12) Bzhosko
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
Labels: OK

#339 (12) Melnikov
  solutions/src/main/java/ru/sberbank/school/task12/Streams.java
  solutions/src/test/java/ru/sberbank/school/task12/StreamsTest.java
Labels: OK

#351 (6, 7, 12) Abdrahimov
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMapImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/AnyStringNumberImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CollectionsServiceFactoryImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/CounterImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/DifferentWordsImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/FileParserImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseIteratorImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/ReverseOrderImpl.java
  solutions/src/main/java/ru/sberbank/school/task07/WordsFrequencyImpl.java
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
  solutions/src/test/java/ru/sberbank/school/task07/CollectionsTest.java
  solutions/src/test/java/ru/sberbank/school/task07/test.txt
  solutions/src/test/java/ru/sberbank/school/task07/test2.txt
  solutions/src/test/java/ru/sberbank/school/task11/StreamsTest.java
Labels: OK

#346 (10, 11, 12) Martyanov
  solutions/src/main/java/ru/sberbank/school/task06/CollectionUtils.java
  solutions/src/main/java/ru/sberbank/school/task06/CountMap.java
  solutions/src/main/java/ru/sberbank/school/task06/MapCounter.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteSerializableManager.java
  solutions/src/main/java/ru/sberbank/school/task09/RouteServiceImpl.java
  solutions/src/main/java/ru/sberbank/school/task10/MyScalableConcurrentThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task10/MyScalableThreadPool.java
  solutions/src/main/java/ru/sberbank/school/task11/Streams.java
  solutions/src/test/java/ru/sberbank/school/task10/MyScalableConcurrentThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task10/MyScalableThreadPoolTest.java
  solutions/src/test/java/ru/sberbank/school/task11/StreamsTest.java
Labels: OK
